name: Create branches

on:
  workflow_dispatch:
#   push:
#     branches:
#       - main

jobs:
  create-branches:
    runs-on: ubuntu-latest
    steps:
      - name: Prompt for number of branches
        id: branch-count
        run: |
          echo ::set-output name=branch-count::$(read -p "Enter the number of branches to create: " && echo $REPLY)
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: main
          fetch-depth: 0
      - name: Create and push branches
        run: |
          for i in $(seq 1 ${{ steps.branch-count.outputs.branch-count }}); do
            branch_name=$(read -p "Enter name for branch $i: " && echo $REPLY)
            git branch $branch_name
            git push origin $branch_name
          done
