name: Create branches

on:
  workflow_dispatch:
#   push:
#     branches:
#       - main

jobs:
  create-branches:
    runs-on: ubuntu-latest
    
    permissions:
      actions: write
      checks: write
      contents: write
      deployments: write
      id-token: write
      issues: write
      discussions: write
      packages: write
      pages: write
      pull-requests: write
      repository-projects: write
      security-events: write
      statuses: write
  
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: main
          fetch-depth: 0
      - name: Create production branch
        run: git branch production
      - name: Push production
        run: git push origin production
      - name: Create dev branch
        run: git branch dev
      - name: Push dev
        run: git push origin dev
