name: Create branches

on: 
  workflow_dispatch:
    inputs:
      branch1:
        description: 'Second branch name'     
        required: true
        default: 'dev'
      tags:
        description: 'Test scenario tags'  

jobs:
  printInputs:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "Log level: ${{ github.event.inputs.logLevel }}"
        echo "Tags: ${{ github.event.inputs.tags }}" 


# on:
#   workflow_dispatch:
#     inputs:
#       environment:
#         description: 'Define env name'     
#         required: true
#         default: 'prod'
#       branch:
#         description: 'Define branch name'     
#         required: true
#         default: 'master'

# jobs:
#   create-branches:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2
#         with:
#           ref: main
#           fetch-depth: 0
#       - name: Create branch 
#         run: git branch "Branch: ${{ github.event.inputs.branch }}"
#       - name: Push branch A
#         run: git push origin "Branch: ${{ github.event.inputs.branch }}"

