name: Create branches

on: 
  workflow_dispatch:
    inputs:
      branch2:
        description: 'Second branch name'     
        required: true
        default: 'dev'
      branch3:
        description: 'Third branch name'
        required: true
        default: 'production'
      branch4:
        description: 'Third branch name'
        required: false
        default: 'production'

permissions:
  actions: write
  checks: write
  contents: write
  deployments: write
  id-token: write
  issues: write
  discussions: write
  packages: write
  pages: write
  pull-requests: write
  repository-projects: write
  security-events: write
  statuses: write

jobs:
  create-branches:
    runs-on: ubuntu-latest
    steps:
    - name: Create branch 2
    - run: |
        git branch ${{ github.event.inputs.branch2 }}

# jobs:
#   create-branches:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2
#         with:
#           ref: main
#           fetch-depth: 0
#       - name: Create branch 
#         run: git branch "Branch: ${{ github.event.inputs.branch }}"
#       - name: Push branch A
#         run: git push origin "Branch: ${{ github.event.inputs.branch }}"

