name: Create branches

on:
  push:
    branches:
      - main

jobs:
  create-branches:
    runs-on: ubuntu-latest
    
    permissions:
      actions: write
      checks: write
      contents: write
      deployments: write
      id-token: write
      issues: write
      discussions: write
      packages: write
      pages: write
      pull-requests: write
      repository-projects: write
      security-events: write
      statuses: write
  
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create branch A
        run: git checkout -b branch-A
      - name: Push branch A
        run: git push origin branch-A
      - name: Create branch B
        run: git checkout -b branch-B
      - name: Push branch B
        run: git push origin branch-B
      - name: Create branch C
        run: git checkout -b branch-C
      - name: Push branch C
        run: git push origin branch-C
