name: Create branches

on: 
  workflow_dispatch:
    inputs:
      branch2:
        description: 'Second branch name'     
        required: true
        default: 'dev'
      branch3:
        description: 'Third branch name'
        required: true
        default: 'production'
      branch4:
        description: 'Fourth branch name'
        required: false
        default: ''

permissions:
  actions: write
  checks: write
  contents: write
  deployments: write
  id-token: write
  issues: write
  discussions: write
  packages: write
  pages: write
  pull-requests: write
  repository-projects: write
  security-events: write
  statuses: write

jobs:
  create-branches:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: main
          fetch-depth: 0
      - name: Create branch 2
        run: git branch ${{ github.event.inputs.branch2 }}
      - name: Push branch 2
        run: git push origin ${{ github.event.inputs.branch2 }}
      - name: Create branch 3
        run: git branch ${{ github.event.inputs.branch3 }}
      - name: Push branch 3
        run: git push origin ${{ github.event.inputs.branch3 }}
      - name: Create branch 4
        run: git branch ${{ github.event.inputs.branch4 }}
      - name: Push branch 4
        run: git push origin ${{ github.event.inputs.branch4 }}
      - name: install HubFlow
        run: cd GitFlow
        run: git hf init
      # - name: Set GITHUB_TOKEN
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.TOKEN }}
      # - name: Add branch protections
      #   uses: octokit/request-action@v2.x
      #   with:
      #     route: PUT /repos/:owner/:repo/branches/${{ github.event.inputs.branch2 }}/protection
      #     headers: |
      #       Accept: application/vnd.github.luke-ca ge-preview+json
      #       Authorization: ${{ secrets.GITHUB_TOKEN }}
      #     data: |
      #       {
      #         "required_status_checks": {
      #           "strict": true,
      #           "contexts": ["ci/circleci: build"]
      #         },
      #         "enforce_admins": true
      #       }

